version: '3.9'

services:
  base:
    build:
      context: ./
      dockerfile: ./docker/base/Dockerfile
    image: ecoin-base
  app:
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
    image: ecoin-dev
    volumes:
      - .:/home/ecoin
    networks:
      - default
  web:
    image: nginx:1.22.0
    volumes:
      - .:/home/ecoin
      - ./docker/dev/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    ports:
      - 80:80
  db:
    image: postgres:14.3
    environment:
      POSTGRES_DB: ecoin
      POSTGRES_USER: ecoin
      POSTGRES_PASSWORD: ecoin
    volumes:
      - ecoin-volume:/var/lib/postgresql/data:rw
    networks:
      - default
volumes:
  ecoin-volume:
